# Generated by Django 4.1.6 on 2023-02-16 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_product"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="Product_category",
            new_name="product_category",
        ),
    ]
